### PR TITLE
Re-sync with uBlock master

### PR DESCRIPTION
**Pull request by ryanbr**
@brave/sec-team just syncing with upstream uBlock

### CODE REVIEW

**Comment by diracdeltas** [comment]
assigning to @snyderp as he seems to be the repo owner here

is this repository supposed to have any diffs from upstream?

**Comment by snyderp** [comment]
@diracdeltas yep, if done correctly, the diffs should be everything thats happened upstream since the last security review (and so the last time uBlock Resources were pulled into the Brave DAT).

**Comment by diracdeltas** [comment]
@snyderp ah right, i remember now. so is the sec review just for everything in src/js/scriplets? (as opposed to this entire PR)

**Comment by snyderp** [comment]
The relevant bits are in src/web_accessible_resources (who files that are replaced) and assets/resources/scriptlets.js (additional JS code that is injected in the page).

Any other changes in the PR can be ignored; but are just here to make keeping in sync with uBO upstream easier

**Comment by diracdeltas** [comment]
the changes in src/web_accessible_resources lgtm and there are apparently no changes in here to assets/resources/scriptlets.js (only to src/js/scriptlets) so this lgtm

**Comment by snyderp** [comment]
LGTM too, just small changes to Google property replacements

**Pull request merged**
