### PR TITLE
Re-sync with uBo master 

### PR DESCRIPTION
**Pull request by ryanbr**
This build fixes twitch.tv ads, and various build/translation fixes.

### CODE REVIEW

**Review by pes10k — APPROVED** [review]
lgtm! (this was a big one!)

**Comment by pes10k** [comment]
thanks @ryanbr !

**Comment by norsehealer** [comment]
ads are back. just had 3 30s ads.

**Comment by sergiotapia-papa** [comment]
Still seeing ads on twitch @ryanbr

**Pull request merged**
