### PR TITLE
Re-sync with uBo master

### PR DESCRIPTION
**Pull request by ryanbr**
New release version of uBO.

New abort-on-stack-trace scriptlet
Syntax and highlighting fixes on `My Rules` tab
More Translation and misc fixes

### CODE REVIEW

**Comment by ryanbr** [comment]
https://github.com/brave/adblock-rust/issues/143  (for the new scriptlet)

**Comment by pes10k** [comment]
@ryanbr thanks for keeping on top of this.  Im not sure i understand the connection with https://github.com/brave/adblock-rust/issues/143 though; are there changes need in adblock-rust then before we merge this in?

From glancing at https://github.com/AdguardTeam/Scriptlets/issues/82 though, I cant see whats needed adblock-rust side.  Its an update to the scriptlet right, not new snytax?

Anywho, if you can let me know about the above when you have a chance, I can finish the review here.  Thanks!

**Comment by ryanbr** [comment]
https://github.com/brave/adblock-rust/issues/143  is only related to the pull request because uBO in these commits rolled out a new feature. Looks like a new scriptlet: https://github.com/brave/uBlock/commit/b735ac6b6abab7d5f45e15bbba3b4ba6cbf43935

Didn't intend to "muddy the waters" of this PR btw.  Should be safe to merge.

**Comment by antonok-edm** [comment]
@pes10k I think you are correct, this should work without any changes in adblock-rust.
@ryanbr the scriptlets all get parsed and served from the ones in this repo, as well as any in the `adblock-resources`. So resyncing should do the trick.

**Review by pes10k — APPROVED** [review]
lgtm

**Pull request merged**
