### PR TITLE
Re-sync with uBo master

### PR DESCRIPTION
**Pull request by ryanbr**
Re-sync with Ubo Master

If someone can review @sec-team

### CODE REVIEW

**Comment by diracdeltas** [comment]
https://github.com/brave/uBlock/pull/5/files#diff-a27ad98cf5a40d0f929c0e6add4ffbedR63 < extraneous logging?

also the iframe should probably be sandboxed

otherwise lgtm, not a big deal either way

**Comment by ryanbr** [comment]
Regarding the iframe sandboxing, Is it something we should log in uBlock upstream? @diracdeltas

**Comment by diracdeltas** [comment]
> Regarding the iframe sandboxing, Is it something we should log in uBlock upstream? @diracdeltas

wouldn't be a bad idea to check. there might be a reason they can't sandbox the iframe here.

**Comment by ryanbr** [comment]
> wouldn't be a bad idea to check. there might be a reason they can't sandbox the iframe here.

Possible to point me to the specific patch/commit I should point them regarding the sandboxing?

**Comment by pes10k** [comment]
As approved by sec-team

**Pull request merged**
