### PR TITLE
Add automated PR creation on upstream updates

### PR DESCRIPTION
**Pull request by itschrishudson**
Resolves https://github.com/brave/devops/issues/6097 for Security Review

Run periodically at a set schedule (started at once per day), and check for updates against the upstream of this fork. 

Updates are parsed for specific files and locations as set in the actions variable `FILES_TO_CHECK`, and if these have been modified, it will trigger the generation of a PR assigned to a specific user defined in `codeowners`.

### CODE REVIEW

**Review by mihaiplesa — APPROVED** [review]

**Review by antonok-edm — COMMENTED** [review]
@pes10k do you know if having this extra commit with the `.github` directory will interfere at all with pulling in the latest upstream changes from uBO? Merging them in should still be fine, but we'll no longer have identical git history (although I guess that's the point of having the fork in the first place)

**Comment by pes10k** [comment]
@antonok-edm i dont think that should cause any problem.  As long as the uBO folks don't create one, should still be easy clean rebasing

**Review by pes10k — APPROVED** [review]
lgtm

**Review by antonok-edm — APPROVED** [review]
sounds good to me then :+1:

**Pull request merged**
